In [1]:
import pandas as pd
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [2]:
dic_listings = pd.read_pickle("../data/pickles/december_listings.pkl")
dic_listings = dic_listings.drop(["name"], axis=1)
dic_reviews = pd.read_csv("../data/2023dic/d_reviews.csv")
dic_reviews = dic_reviews[["listing_id", "id", "date", "reviewer_id", "comments"]]

In [5]:
def preprocess_text(text):
    tokens = word_tokenize(text.lower())
    filtered_tokens = [token for token in tokens if token not in stopwords.words('english')]
    lemmatizer = WordNetLemmatizer()
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in filtered_tokens]
    processed_text = ' '.join(lemmatized_tokens)
    return processed_text

analyzer = SentimentIntensityAnalyzer()
def get_sentiment(text):
    scores = analyzer.polarity_scores(text)
    sentiment = scores['pos']
    return sentiment

In [6]:
# Figure out the sentiment for the two descriptive features
dic_listings["neighborhood_overview"] = dic_listings["neighborhood_overview"].apply(preprocess_text)
dic_listings["neighborhood_overview"] = dic_listings["neighborhood_overview"].apply(get_sentiment)

dic_listings["host_about"] = dic_listings["host_about"].apply(preprocess_text)
dic_listings["host_about"] = dic_listings["host_about"].apply(get_sentiment)

,id,host_id,host_since,host_response_time,property_type,bathrooms_text,first_review,last_review,neighborhood_overview,host_about,...,ferretto_square_distance_km,roma_square_distance_km,rialto_bridge_distance_km,san_marco_square_distance_km,bathrooms,email_verification,phone_verification,work_email_verification,Isole,Terraferma
0,6623,15016,2009-04-27,within a day,Entire Place,single,2009-11-15,2023-10-12,0.166,0.348,...,9.146705,0.668438,0.668334,0.950796,2.0,1.0,1.0,0.0,0.0,0.0
1,6624,15016,2009-04-27,within a day,Entire Place,single,2011-09-29,2023-10-12,0.000,0.348,...,9.023493,0.693982,0.697255,1.050879,2.0,1.0,1.0,0.0,0.0,0.0
2,12074,15016,2009-04-27,within a day,Entire Place,single,2010-04-22,2023-09-26,0.262,0.348,...,9.219285,0.855478,0.497836,0.851855,2.0,1.0,1.0,0.0,0.0,0.0
3,27116,116144,2010-04-30,within an hour,Private Room,private,2010-08-07,2022-11-11,0.193,0.000,...,9.966909,1.360242,0.596532,0.301904,1.0,1.0,1.0,0.0,0.0,0.0
4,44527,120215,2010-05-07,within an hour,Entire Place,single,2011-04-27,2023-11-28,0.312,0.147,...,8.691634,1.166909,1.006614,1.477043,2.0,1.0,1.0,1.0,0.0,0.0